---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hekimog9/public_html/
    - /bin/cp config.php $DEPLOYPATH
    - /bin/cp index_tr.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp stylesheet1.css $DEPLOYPATH
    - /bin/cp -R Header&Footer $DEPLOYPATH
    - /bin/cp -R Main-Nav-Pages $DEPLOYPATH
    - /bin/cp -R Pictures $DEPLOYPATH
    - /bin/cp -R Practice-Areas-Nav-Pages $DEPLOYPATH
    - /bin/cp -R Practice-Areas-Nav-Pages-TR $DEPLOYPATH
    - /bin/cp -R Who-We-Are-Nav-Pages $DEPLOYPATH